
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hardik
 */
public class Map_Source extends javax.swing.JFrame {
    static String source,userid,dest;
    static float dist;
    /**
     * Creates new form Map_Source
     */
    public Map_Source() {
        initComponents();
        jComboBox2.setEnabled(false);
        jTextField1.setVisible(false);
    }
    public static String getSource()
    {
        return source;
    }
    public static String getDest()
    {
        return dest;
    }
    public static String getUserId()
    {
        return userid;
    }
    public static float getDist()
    {
        return dist;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MAP OF DELHI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 11, 340, 37));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHALIMAR BAGH", "PITAMPURA", "JANAKPURI", "KAROL BAGH", "SHAHDRA", "IGI Airport", "LAJPAT NAGAR", "PATPARGANJ", "RAJOURI GARDEN", "HAUZ KHAAS", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 142, 33));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHALIMAR BAGH", "PITAMPURA", "JANAKPURI", "KAROL BAGH", "SHAHDRA", "IGI Airport", "LAJPAT NAGAR", "PATPARGANJ", "RAJOURI GARDEN", "HAUZ KHAAS" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 142, 33));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setLabelFor(jComboBox1);
        jLabel3.setText("Select Source Location");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 200, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setLabelFor(jComboBox2);
        jLabel4.setText("Select Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 220, 30));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("Check Rides");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 170, 36));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hardik\\Desktop\\map_Delhi.JPG")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int i = jComboBox1.getSelectedIndex();
        jComboBox2.removeItemAt(i);
        jComboBox2.setEnabled(true);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int src = jComboBox1.getSelectedIndex();
        int flag=0;
        String alloted;
        source = jComboBox1.getSelectedItem().toString();
        dest = jComboBox2.getSelectedItem().toString();
        dist = Distance.getDistance(source,dest); 
        long time = (long)dist*10000;
        JOptionPane.showMessageDialog(null,"Approximate Distance will be "+dist);
//        displayDist(dist);
//        try
//        {
//            Thread.sleep(2000);
//        }
//        catch(InterruptedException e)
//        {
//            System.out.println(e.getMessage());
//        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hardik?useSSL=false","root","Rssb18@babaji");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select * from drivers order by rating desc;");
            while(rs.next())
            {
                if(rs.getInt("flag")==1)
                    {
                        String datasrc = rs.getString("loc");
                    if(source.equalsIgnoreCase(datasrc))
                    {
                        //if(rs.getInt("flag")==1)
                         userid = rs.getString("userid");
                        flag=1;
                        dispose();
                        break;
                    }
                }
            }
            if(flag==0)
            {
                JOptionPane.showMessageDialog(null,"No Driver available at this location.\nNearest driver will arrive shortly\nDetails will follow");
                String nearest = Distance.getNearest(source);
                System.out.println("1. "+nearest);
                Statement stmt1 = conn.createStatement();
                ResultSet rs1 = stmt1.executeQuery("select * from drivers where flag = 1 and loc = \""+nearest+"\" order by rating desc;");
               boolean nxt= rs1.next();
               if(nxt)
               {
                alloted = rs1.getString("name");
                userid = rs1.getString("userid");
                Statement stmt2 = conn.createStatement();
                stmt2.executeUpdate("update drivers set loc = \""+source+"\" , flag=0 where name = \""+alloted+"\" ;");
//                this.dispose();
                new First_Allot().setVisible(true);
                 try
                {
                  Thread.sleep(3500);
                  JOptionPane.showMessageDialog(null,"Ride has started!\nWish you a safe Journey");
                 }
                catch(InterruptedException e)
                {
                    System.out.println(e);
                }
                try
                {
                    
                  Thread.sleep(30000);
                  
                }catch(InterruptedException e)
                {
                    System.out.println(e);
                }
                 JOptionPane.showMessageDialog(null,"Ride has ended.");
                   Statement stmt4=conn.createStatement();
                stmt4.executeUpdate("update drivers set flag=1, loc = \""+dest+"\" where userid = \""+userid+"\";");
               }
                /*if(rs1.next())
                {
                    Statement stmt2 = conn.createStatement();
                    stmt2.executeUpdate("update drivers set loc = \""+source+"\" where loc = \""+ nearest+"\" ;");
                    new First_Allot().setVisible(true);
//                    break;
                }*/
                else
                {
                    System.out.println("in alternate allot");
//                    this.dispose();
                    new Alternate_Allot(source);
                }
            }
            if(flag==1)
            {
                new Available_Drivers().setVisible(true);
               
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map_Source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map_Source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map_Source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map_Source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map_Source().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
