
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hardik
 */
public class Register extends javax.swing.JFrame {
    int flag1=0;
    static int alpha=1;
    //RandomNum obj = new RandomNum();
    static int otp1 = RandomNum.getRandom(); 
    static int otp=otp1;
    String name,username,pass,contact,email,pass1;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
//        jTextField3.setEnabled(false);
        jPasswordField1.setEnabled(false);
        jPasswordField2.setEnabled(false);
//        jTextField4.setEnabled(false);
        otpCheker.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }
    
    public static int getotp()
    {
        return otp;
    }
    public void NextButton()
    {
        jButton1.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        usernameCheck = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        otpCheker = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN-UP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 22, 129, 39));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 79, 86, 28));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 139, 86, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 199, 86, 27));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 40));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter Phone No.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 314, 150, 30));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("Next");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 432, 88, 37));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 79, 129, 28));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 139, 129, 30));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 199, 129, 27));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 256, 129, 27));

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 314, 129, 27));

        usernameCheck.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        usernameCheck.setText("Check Availability");
        usernameCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usernameCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameCheckActionPerformed(evt);
            }
        });
        getContentPane().add(usernameCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 135, -1, -1));

        jButton2.setText("Validate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 100, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 186, 176, 30));

        otpCheker.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        otpCheker.setText("SEND OTP");
        otpCheker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        otpCheker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpChekerActionPerformed(evt);
            }
        });
        getContentPane().add(otpCheker, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, 25));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 227, 140, 27));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Email Id");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 372, 86, -1));

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 372, 129, 27));

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 432, 86, 37));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hardik\\Desktop\\gradient.JPG")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hardik?useSSL=false","root","Rssb18@babaji");
            Statement stmt = conn.createStatement();
            email = jTextField4.getText();
            stmt.executeUpdate("insert into login values(\""+name+"\",\""+username+"\",\""+pass+"\",\""+contact+"\",\""+email+"\","+0+");");
            JOptionPane.showMessageDialog(this,"Details inserted Successfully!");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameCheckActionPerformed
       
       name = jTextField1.getText();
       //jTextField2.setEnabled(true);
       username = jTextField2.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hardik?useSSL=false","root","Rssb18@babaji");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select * from login;");
            while(rs.next())
            {
                String user = rs.getString("username");
                //System.out.println(user);
                if((user.equals(username)))
                {
                    jLabel7.setText("Username Already Taken!");
                    JOptionPane.showMessageDialog(this,"Username Already Taken!");
                    flag1=1;
                    //break;
                    this.dispose();
                    Register frame2 = new Register();
                    frame2.setVisible(true);
                    frame2.jTextField1.setText(name);
                }
            }
            if(flag1!=1)
                {
                    jLabel7.setText("Username Available!");
                    jPasswordField1.setEnabled(true);
                    jPasswordField2.setEnabled(true);
                    jButton2.setEnabled(true);
                    //jButton1.setEnabled(true);
                }
            conn.close();
        }catch(Exception e)
        {
            System.out.println(e);
        }
        /*int counter=0;
//                username = jTextField2.getText();
//                name = jTextField1.getText();
            if(flag1!=1)
            {
            try
                {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hardik?useSSL=false","root","Rssb18@babaji");
                Statement stmt = conn.createStatement();
                stmt.executeQuery("select * from login;");
                //jPasswordField1.setEnabled(true);
                char s[] = jPasswordField1.getPassword();
                pass = new String(s);
                //jPasswordField2.setEnabled(true);
                char s1[] = jPasswordField2.getPassword();
                String pass1 = new String(s1);
                if(pass.equals(pass1))
                {
                    jLabel8.setText("Passwords Match!");
                    jTextField3.setVisible(true);
                    jButton3.setVisible(true);
                    counter=1;
                }
                else
                {
                    jLabel8.setText("Passwords do not match");
                }
                if(counter==1)
                {
                    contact = jTextField3.getText();
                    JOptionPane.showMessageDialog(this,"Your OTP is " + otp);
                    //this.setVisible(false);
                    OTP frame2 = new OTP();
                    frame2.setVisible(true);
                    jButton1.setEnabled(true);
                    }
                conn.close();
                }catch(Exception e)
                {
                    System.out.println(e);
                }
}*/
        
        
    }//GEN-LAST:event_usernameCheckActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
       
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
      
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void otpChekerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpChekerActionPerformed
                int counter=0;
                char s[] = jPasswordField1.getPassword();
                pass = new String(s);
                char s1[] = jPasswordField2.getPassword();
                pass1 = new String(s1);
                if(pass.equals(pass1))
                {
                    jLabel8.setText("Passwords Match!");
                    jTextField4.setEnabled(true);
                    jTextField3.setEnabled(true);
                    counter=1;
                }
                else
                {
                    jLabel8.setText("Passwords do not match");
                }
                if(counter==1)
                {
                    contact = jTextField3.getText();
                    JOptionPane.showMessageDialog(this,"Your OTP is " + otp);
                    //this.setVisible(false);
//                    this.setVisible(false);
                    new OTP_for_Next().setVisible(true);
                    if(alpha==1)
                    {
                        jButton1.setEnabled(true);
                    }
                }
    }//GEN-LAST:event_otpChekerActionPerformed

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1StateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Welcome_Page wel = new Welcome_Page();
    wel.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String email=jTextField4.getText();
        String num = jTextField3.getText();
        char s[] = jPasswordField1.getPassword();
        int flag2=0;
        int z = s.length;
        if(z<5)
        {
            flag2=1;
            JOptionPane.showMessageDialog(this,"Invalid Password!\nEnter minimum 5 characters.");
        }
        int x = num.length();
        int flag1=0;
        if(x!=10)
        {
            JOptionPane.showMessageDialog(this,"Invalid Phone Number!\nEnter Again");
            flag1=1;
        }
        int flag=0;
        int n= email.indexOf('@');
        int m = email.indexOf(".com");
        if(n<0 || m<0 ||m-n<=1)
        {
            JOptionPane.showMessageDialog(this,"Invalid Email Id!\nEnter Again");
            flag=1;
        }
        if(flag==0 && flag1==0 && flag2==0)
        {
            otpCheker.setEnabled(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton otpCheker;
    private javax.swing.JButton usernameCheck;
    // End of variables declaration//GEN-END:variables
}
